### ISSUE TITLE
Nested dimension tracking fails for constants

### ISSUE THREAD

**Issue by jackvreeken** [pymoca/pymoca#155]
See branch `fix-nested-constant-ref` for a failing test case. The Modelica model in that test that fails is:

```Modelica
package P1
  constant Real p = 1;
end P1;

model A
  parameter Real q = P1.p;
end A;

model Test
  A a1;
  A a2;
end Test;
```

**Comment by jackvreeken** [comment]
@AnneHommelberg Any ideas on what is going wrong? Test.a1.P1.p still seems to have the right .dimensions property, but the second reference in a2 makes that one fail (one array/list too deep).

**Comment by AnneHommelberg** [comment]
@jackvreeken 
I've found the error and pushed a commit to the fix-nested-constant-ref branch that should fix it. 
In short: 
- when the parser created a symbol the dimension was still a simple list containing primary values. 
- In tree.py -> flatten_symbols() these were combined into a list of lists by adding an extra list layer when necessary.
- Since this method uses recursion and the "new" flat_sym is a simple reference assignment instead of a copy (line 488), after which the dimensions are then changed, in the test case we passed the addition of a list layer twice. 

I've now changed the code to immediately create all symbols with a dimension that is a list of lists, so flatten_symbol no longer needs to add a list layer, but only needs to combine the lists. This makes a lot more sense than the old set-up, not sure why I did it that way in the original implementation... 

The test case you added still fails on the assertion checks in the test case itself, but it does successfully get through the flattening / model generation. All other test cases (in gen_casadi_test) should be successful.
