### ISSUE TITLE
Current ANTLR generated code not supported in Python 3.12

### ISSUE THREAD

**Issue by jackvreeken** [pymoca/pymoca#288]
I see `pymoca\src\pymoca\generated\ModelicaLexer.py:4: DeprecationWarning: typing.io is deprecated, import directly from typing instead. typing.io will be removed in Python 3.12.` in my test logs. I guess that means we should update ANTLR (and the generated code part of this repo)

**Comment by kentrutan** [comment]
@jackvreeken I would be happy to take care of this one if you don't want to do it. Just assign to me if you agree.

I have been running ANTLR 4.9 on my development branches for quite some time, and there are several releases beyond that now. Was planning on including the update in a Speedy ANTLR PR, but that one turned out to be a bigger task because I need to make some PRs to Speedy ANTLR to support features Pymoca uses. Speaking of Speedy ANTLR, it would be good to have some setup/packaging modernization done before I add a bunch more complexity with compiled code.

**Comment by kentrutan** [comment]
@jackvreeken Looks like October is the current plan for 3.12 release, so I'll get on this one after cache code review.

**Comment by jackvreeken** [comment]
Sounds good! I just had the motivation and time last week to work on Pymoca things. Please don't feel any pressure to also review it ASAP, I'll be quite a bit more busy myself as well next couple of weeks :)
