### ISSUE TITLE
Update Road Map

### ISSUE THREAD

**Issue by jgoppert** [pymoca/pymoca#72]
The Road Map on the README needs some work. What are our current long-term goals? For me it would be:

## DONE
1. Compiler support for most language elements.
2. Sympy back-end support for basic simulation and symbolic expression creation.
3. Casadi back-end DAE symbolic expression creation.

## TODO
1. Add Casadi based simulation support.
2. Handle when, if, and discrete time language elements in the compiler.
3. Add a method of serializing a flattened tree and reading it back from disk (possibly XML).
4. Support for higher dimensional arrays.
5. Support all of Modelica Standard Library

**Comment by jbaayen** [comment]
Folks, I am reopening this because we should be having a trilateral discussions about the future of pymol^Hca (James, Deltares, and KISTERS). 

I propose to set a day and time for a fixed (bi)weekly "Skype standup" to update each other and discuss development directions. One meeting is more efficient than up to (4 take 2) = 6 1:1 discussions.

Would you guys be in on this?

I am in CET and knowing that @vdwees (usually) is in UTC-5, I'd suggest a time slot of 16:00 - 16:30 CET. I have no preference with regards to days.

**Comment by jgoppert** [comment]
I agree we could benefit from this. I'm on EST, that time slot is good for me. I would prefer Tuesday or Thursday, but can make any day but Monday work.

**Comment by jbaayen** [comment]
Cool. Between Tuesday and Thursday, I prefer Tuesday. We could have our first meeting Tuesday the 13th, 16:00-16:30 CET/10:00-10:30 EST.

@jackvreeken @vdwees would you be available during this slot?

**Comment by jackvreeken** [comment]
Sure, I'm up for it.

**Comment by vdwees** [comment]
I am available too.
